{% set python_min = "3.11" %}
{% set name = "sfrmaker" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sfrmaker-{{ version }}.tar.gz
  sha256: 6ba4016ea4ea127e31e1cb97657eea2a954b1bbfd7e7b6139ce77403097ac8ff

build:
  entry_points:
    - get-modflow = flopy.utils.get_modflow:cli_main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - pip
  run:
    - python >={{ python_min }}
    - geopandas
    - gis-utils
    - fiona
    - flopy
    - modflow-export
    - netcdf4
    - numpy
    - pandas
    - pyproj
    - pyyaml
    - rasterio
    - rasterstats
    - rtree
    - scipy
    - shapely
    - xarray

test:
  imports:
    - sfrmaker
  commands:
    - pip check
    - get-modflow --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/DOI-USGS/sfrmaker.git
  summary: Rapid construction of MODFLOW SFR Package input from hydrography data
  license: CC0-1.0
  license_file: LICENSE.md
  doc_url: https://doi-usgs.github.io/sfrmaker/latest/

extra:
  recipe-maintainers:
    - aleaf
