{% set name = "sfrmaker" %}
{% set version = "0.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sfrmaker-{{ version }}.tar.gz
  sha256: 16841792c16926eb27954982d73c8af1bc8688556070e3a1a64de9dc4ab6eb64

build:
  entry_points:
    - get-modflow = flopy.utils.get_modflow:cli_main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - setuptools >=61
    - pip
  run:
    - python >=3.11
    - geopandas
    - gis-utils
    - fiona
    - flopy
    - modflow-export
    - netcdf4
    - numpy
    - pandas
    - pyproj
    - pyyaml
    - rasterio
    - rasterstats
    - rtree
    - scipy
    - shapely
    - xarray

test:
  imports:
    - sfrmaker
  commands:
    - pip check
    - get-modflow --help
  requires:
    - pip

about:
  home: https://github.com/DOI-USGS/sfrmaker.git
  summary: Rapid construction of MODFLOW SFR Package input from hydrography data
  license: CC0-1.0
  license_file: LICENSE.md
  doc_url: https://doi-usgs.github.io/sfrmaker/latest/

extra:
  recipe-maintainers:
    - aleaf
    - jdhughes-usgs
